export const STATE_STARTED = "STATE_STARTED";
export const STATE_STORE_SNAPSHOT = "STATE_STORE_SNAPSHOT";
export const STATE_ERROR_IN_MAIN = "STATE_ERROR_IN_MAIN";
export const STATE_BIN_PATH = "STATE_BIN_PATH";
